- become: yes
  hosts: all
  name: install
  tasks:
    - name: Install amazon-linux-extras
      ansible.builtin.shell: amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2

    - name: Install lamp
      yum:
        name:
          - git
          - httpd
          - mariadb-server
        update_cache: yes
        state: latest
    
    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started

    - name: Enable service mariadb, and not touch the state
      ansible.builtin.service:
        name: mariadb
        enabled: yes
        state: started

    - name: Add the user 'ec2-user' with a specific uid and a primary group of 'apache'
      ansible.builtin.user:
        name: ec2-user
        comment: ec2-user
        group: apache

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/www
        owner: ec2-user
        group: apache
        mode: '2775'

    - name: Create phpinfo
      ansible.builtin.shell: echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php

    - name: Checkout from github 
      ansible.builtin.git:
        repo: https://github.com/loliva/phpcode.git
        dest: /var/www/html/phpcode
        

